name = "Tools"
uuid = "75d8cae4-cbd2-49ea-8ed4-9d3aee9dbe67"
authors = ["KronosTheLate"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
